name: Run ASM output

on:
  push:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get -y install gcc nasm

    - name: make debug
      run: make debug